# Generated by Django 2.2.7 on 2019-12-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191130_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityweather',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
